<?php

// Data functions (insert, update, delete, form) for table Computadora

// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

function Computadora_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Computadora');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['Empleado'] = $_REQUEST['Empleado'];
		if($data['Empleado'] == empty_lookup_value) { $data['Empleado'] = ''; }
	$data['Marca'] = $_REQUEST['Marca'];
		if($data['Marca'] == empty_lookup_value) { $data['Marca'] = ''; }
	$data['Modelo'] = $_REQUEST['Modelo'];
		if($data['Modelo'] == empty_lookup_value) { $data['Modelo'] = ''; }
	$data['Serie'] = $_REQUEST['Serie'];
		if($data['Serie'] == empty_lookup_value) { $data['Serie'] = ''; }
	$data['Headset'] = $_REQUEST['Headset'];
		if($data['Headset'] == empty_lookup_value) { $data['Headset'] = ''; }
	$data['Monitor'] = $_REQUEST['Monitor'];
		if($data['Monitor'] == empty_lookup_value) { $data['Monitor'] = ''; }
	$data['informacion1'] = $_REQUEST['informacion1'];
		if($data['informacion1'] == empty_lookup_value) { $data['informacion1'] = ''; }
	$data['informacion2'] = $_REQUEST['informacion2'];
		if($data['informacion2'] == empty_lookup_value) { $data['informacion2'] = ''; }
	$data['NombreComp'] = $_REQUEST['NombreComp'];
		if($data['NombreComp'] == empty_lookup_value) { $data['NombreComp'] = ''; }
	$data['Antivirus'] = $_REQUEST['Antivirus'];
		if($data['Antivirus'] == empty_lookup_value) { $data['Antivirus'] = ''; }
	$data['TeamviewerID'] = $_REQUEST['TeamviewerID'];
		if($data['TeamviewerID'] == empty_lookup_value) { $data['TeamviewerID'] = ''; }
	$data['Notas'] = br2nl($_REQUEST['Notas']);
	if($data['Empleado']== '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Nombre Empleado': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['Marca']== '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Marca Comp.': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['Serie']== '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " '# Serie': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: Computadora_before_insert
	if(function_exists('Computadora_before_insert')) {
		$args = array();
		if(!Computadora_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Computadora', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: Computadora_after_insert
	if(function_exists('Computadora_after_insert')) {
		$res = sql("select * from `Computadora` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Computadora_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Computadora', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) Computadora_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function Computadora_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Computadora_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Computadora');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Computadora' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Computadora' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Computadora_before_delete
	if(function_exists('Computadora_before_delete')) {
		$args=array();
		if(!Computadora_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Computadora` where `id`='$selected_id'", $eo);

	// hook: Computadora_after_delete
	if(function_exists('Computadora_after_delete')) {
		$args=array();
		Computadora_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Computadora' and pkValue='$selected_id'", $eo);
}

function Computadora_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Computadora');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Computadora' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Computadora' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Empleado'] = makeSafe($_REQUEST['Empleado']);
		if($data['Empleado'] == empty_lookup_value) { $data['Empleado'] = ''; }
	if($data['Empleado']=='') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombre Empleado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['Marca'] = makeSafe($_REQUEST['Marca']);
		if($data['Marca'] == empty_lookup_value) { $data['Marca'] = ''; }
	if($data['Marca']=='') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Marca Comp.': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['Modelo'] = makeSafe($_REQUEST['Modelo']);
		if($data['Modelo'] == empty_lookup_value) { $data['Modelo'] = ''; }
	$data['Serie'] = makeSafe($_REQUEST['Serie']);
		if($data['Serie'] == empty_lookup_value) { $data['Serie'] = ''; }
	if($data['Serie']=='') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '# Serie': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['Headset'] = makeSafe($_REQUEST['Headset']);
		if($data['Headset'] == empty_lookup_value) { $data['Headset'] = ''; }
	$data['Monitor'] = makeSafe($_REQUEST['Monitor']);
		if($data['Monitor'] == empty_lookup_value) { $data['Monitor'] = ''; }
	$data['informacion1'] = makeSafe($_REQUEST['informacion1']);
		if($data['informacion1'] == empty_lookup_value) { $data['informacion1'] = ''; }
	$data['informacion2'] = makeSafe($_REQUEST['informacion2']);
		if($data['informacion2'] == empty_lookup_value) { $data['informacion2'] = ''; }
	$data['NombreComp'] = makeSafe($_REQUEST['NombreComp']);
		if($data['NombreComp'] == empty_lookup_value) { $data['NombreComp'] = ''; }
	$data['Antivirus'] = makeSafe($_REQUEST['Antivirus']);
		if($data['Antivirus'] == empty_lookup_value) { $data['Antivirus'] = ''; }
	$data['TeamviewerID'] = makeSafe($_REQUEST['TeamviewerID']);
		if($data['TeamviewerID'] == empty_lookup_value) { $data['TeamviewerID'] = ''; }
	$data['Notas'] = br2nl(makeSafe($_REQUEST['Notas']));
	$data['actualizado'] = parseCode('<%%editingDate%%>', false);
	$data['selectedID'] = makeSafe($selected_id);

	// hook: Computadora_before_update
	if(function_exists('Computadora_before_update')) {
		$args = array();
		if(!Computadora_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `Computadora` set       `Empleado`=' . (($data['Empleado'] !== '' && $data['Empleado'] !== NULL) ? "'{$data['Empleado']}'" : 'NULL') . ', `Marca`=' . (($data['Marca'] !== '' && $data['Marca'] !== NULL) ? "'{$data['Marca']}'" : 'NULL') . ', `Modelo`=' . (($data['Modelo'] !== '' && $data['Modelo'] !== NULL) ? "'{$data['Modelo']}'" : 'NULL') . ', `Serie`=' . (($data['Serie'] !== '' && $data['Serie'] !== NULL) ? "'{$data['Serie']}'" : 'NULL') . ', `Headset`=' . (($data['Headset'] !== '' && $data['Headset'] !== NULL) ? "'{$data['Headset']}'" : 'NULL') . ', `Monitor`=' . (($data['Monitor'] !== '' && $data['Monitor'] !== NULL) ? "'{$data['Monitor']}'" : 'NULL') . ', `informacion1`=' . (($data['informacion1'] !== '' && $data['informacion1'] !== NULL) ? "'{$data['informacion1']}'" : 'NULL') . ', `informacion2`=' . (($data['informacion2'] !== '' && $data['informacion2'] !== NULL) ? "'{$data['informacion2']}'" : 'NULL') . ', `NombreComp`=' . (($data['NombreComp'] !== '' && $data['NombreComp'] !== NULL) ? "'{$data['NombreComp']}'" : 'NULL') . ', `Antivirus`=' . (($data['Antivirus'] !== '' && $data['Antivirus'] !== NULL) ? "'{$data['Antivirus']}'" : 'NULL') . ', `TeamviewerID`=' . (($data['TeamviewerID'] !== '' && $data['TeamviewerID'] !== NULL) ? "'{$data['TeamviewerID']}'" : 'NULL') . ', `Notas`=' . (($data['Notas'] !== '' && $data['Notas'] !== NULL) ? "'{$data['Notas']}'" : 'NULL') . ', `actualizado`=' . "'{$data['actualizado']}'" . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="Computadora_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Computadora_after_update
	if(function_exists('Computadora_after_update')) {
		$res = sql("SELECT * FROM `Computadora` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Computadora_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='Computadora' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function Computadora_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Computadora');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Monitor
	$combo_Monitor = new Combo;
	$combo_Monitor->ListType = 0;
	$combo_Monitor->MultipleSeparator = ', ';
	$combo_Monitor->ListBoxHeight = 10;
	$combo_Monitor->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Computadora.Monitor.csv')) {
		$Monitor_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Computadora.Monitor.csv')));
		$combo_Monitor->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($Monitor_data)));
		$combo_Monitor->ListData = $combo_Monitor->ListItem;
	}else{
		$combo_Monitor->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Si;;No")));
		$combo_Monitor->ListData = $combo_Monitor->ListItem;
	}
	$combo_Monitor->SelectName = 'Monitor';
	// combobox: Antivirus
	$combo_Antivirus = new Combo;
	$combo_Antivirus->ListType = 0;
	$combo_Antivirus->MultipleSeparator = ', ';
	$combo_Antivirus->ListBoxHeight = 10;
	$combo_Antivirus->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Computadora.Antivirus.csv')) {
		$Antivirus_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Computadora.Antivirus.csv')));
		$combo_Antivirus->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($Antivirus_data)));
		$combo_Antivirus->ListData = $combo_Antivirus->ListItem;
	}else{
		$combo_Antivirus->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Windows Defender;;Sophos;;Otros")));
		$combo_Antivirus->ListData = $combo_Antivirus->ListItem;
	}
	$combo_Antivirus->SelectName = 'Antivirus';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Computadora' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Computadora' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `Computadora` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Computadora_view.php', false);
		}
		$combo_Monitor->SelectedData = $row['Monitor'];
		$combo_Antivirus->SelectedData = $row['Antivirus'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_Monitor->SelectedText = ( $_REQUEST['FilterField'][1]=='7' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_Antivirus->SelectedText = ( $_REQUEST['FilterField'][1]=='11' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_Monitor->Render();
	$combo_Antivirus->Render();

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Computadora_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Computadora_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Computadora_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Computadora_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Computadora_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#Empleado').replaceWith('<div class=\"form-control-static\" id=\"Empleado\">' + (jQuery('#Empleado').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Marca').replaceWith('<div class=\"form-control-static\" id=\"Marca\">' + (jQuery('#Marca').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Modelo').replaceWith('<div class=\"form-control-static\" id=\"Modelo\">' + (jQuery('#Modelo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Serie').replaceWith('<div class=\"form-control-static\" id=\"Serie\">' + (jQuery('#Serie').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Headset').replaceWith('<div class=\"form-control-static\" id=\"Headset\">' + (jQuery('#Headset').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Monitor').replaceWith('<div class=\"form-control-static\" id=\"Monitor\">' + (jQuery('#Monitor').val() || '') + '</div>'); jQuery('#Monitor-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#informacion1').replaceWith('<div class=\"form-control-static\" id=\"informacion1\">' + (jQuery('#informacion1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#informacion2').replaceWith('<div class=\"form-control-static\" id=\"informacion2\">' + (jQuery('#informacion2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#NombreComp').replaceWith('<div class=\"form-control-static\" id=\"NombreComp\">' + (jQuery('#NombreComp').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Antivirus').replaceWith('<div class=\"form-control-static\" id=\"Antivirus\">' + (jQuery('#Antivirus').val() || '') + '</div>'); jQuery('#Antivirus-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#TeamviewerID').replaceWith('<div class=\"form-control-static\" id=\"TeamviewerID\">' + (jQuery('#TeamviewerID').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Notas').replaceWith('<div class=\"form-control-static\" id=\"Notas\">' + (jQuery('#Notas').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Monitor)%%>', $combo_Monitor->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Monitor)%%>', $combo_Monitor->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Antivirus)%%>', $combo_Antivirus->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Antivirus)%%>', $combo_Antivirus->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Empleado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Marca)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Modelo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Serie)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Headset)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Monitor)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(informacion1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(informacion2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(NombreComp)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Antivirus)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(TeamviewerID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Notas)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(actualizado)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Empleado)%%>', safe_html($urow['Empleado']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Empleado)%%>', html_attr($row['Empleado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Empleado)%%>', urlencode($urow['Empleado']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Marca)%%>', safe_html($urow['Marca']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Marca)%%>', html_attr($row['Marca']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Marca)%%>', urlencode($urow['Marca']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Modelo)%%>', safe_html($urow['Modelo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Modelo)%%>', html_attr($row['Modelo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Modelo)%%>', urlencode($urow['Modelo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Serie)%%>', safe_html($urow['Serie']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Serie)%%>', html_attr($row['Serie']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Serie)%%>', urlencode($urow['Serie']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Headset)%%>', safe_html($urow['Headset']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Headset)%%>', html_attr($row['Headset']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Headset)%%>', urlencode($urow['Headset']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Monitor)%%>', safe_html($urow['Monitor']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Monitor)%%>', html_attr($row['Monitor']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Monitor)%%>', urlencode($urow['Monitor']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(informacion1)%%>', safe_html($urow['informacion1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(informacion1)%%>', html_attr($row['informacion1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(informacion1)%%>', urlencode($urow['informacion1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(informacion2)%%>', safe_html($urow['informacion2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(informacion2)%%>', html_attr($row['informacion2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(informacion2)%%>', urlencode($urow['informacion2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(NombreComp)%%>', safe_html($urow['NombreComp']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(NombreComp)%%>', html_attr($row['NombreComp']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(NombreComp)%%>', urlencode($urow['NombreComp']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Antivirus)%%>', safe_html($urow['Antivirus']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Antivirus)%%>', html_attr($row['Antivirus']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Antivirus)%%>', urlencode($urow['Antivirus']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(TeamviewerID)%%>', safe_html($urow['TeamviewerID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(TeamviewerID)%%>', html_attr($row['TeamviewerID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TeamviewerID)%%>', urlencode($urow['TeamviewerID']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(Notas)%%>', safe_html($urow['Notas']), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(Notas)%%>', html_attr($row['Notas']), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(Notas)%%>', urlencode($urow['Notas']), $templateCode);
		$templateCode = str_replace('<%%VALUE(actualizado)%%>', safe_html($urow['actualizado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(actualizado)%%>', urlencode($urow['actualizado']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Empleado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Empleado)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Marca)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Marca)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Modelo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Modelo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Serie)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Serie)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Headset)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Headset)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Monitor)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Monitor)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(informacion1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(informacion1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(informacion2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(informacion2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(NombreComp)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(NombreComp)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Antivirus)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Antivirus)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(TeamviewerID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TeamviewerID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Notas)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Notas)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(actualizado)%%>', '<%%editingDate%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(actualizado)%%>', urlencode('<%%editingDate%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Computadora');
	if($selected_id) {
		$jdata = get_joined_record('Computadora', $selected_id);
		if($jdata === false) $jdata = get_defaults('Computadora');
		$rdata = $row;
	}
	$templateCode .= loadView('Computadora-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Computadora_dv
	if(function_exists('Computadora_dv')) {
		$args=array();
		Computadora_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>