<?php
// This script and data application were generated by AppGini 5.84
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Computadora.php");
	include("$currDir/Computadora_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Computadora');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Computadora";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Computadora`.`id`" => "id",
		"`Computadora`.`Empleado`" => "Empleado",
		"`Computadora`.`Marca`" => "Marca",
		"`Computadora`.`Modelo`" => "Modelo",
		"`Computadora`.`Serie`" => "Serie",
		"`Computadora`.`Hedset`" => "Hedset",
		"`Computadora`.`Monitor`" => "Monitor",
		"`Computadora`.`campo1`" => "campo1",
		"`Computadora`.`campo2`" => "campo2",
		"`Computadora`.`NombreComp`" => "NombreComp",
		"`Computadora`.`Antivirus`" => "Antivirus",
		"`Computadora`.`TeamviewerID`" => "TeamviewerID",
		"`Computadora`.`Notas`" => "Notas",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Computadora`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => '`Computadora`.`TeamviewerID`',
		13 => 13,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Computadora`.`id`" => "id",
		"`Computadora`.`Empleado`" => "Empleado",
		"`Computadora`.`Marca`" => "Marca",
		"`Computadora`.`Modelo`" => "Modelo",
		"`Computadora`.`Serie`" => "Serie",
		"`Computadora`.`Hedset`" => "Hedset",
		"`Computadora`.`Monitor`" => "Monitor",
		"`Computadora`.`campo1`" => "campo1",
		"`Computadora`.`campo2`" => "campo2",
		"`Computadora`.`NombreComp`" => "NombreComp",
		"`Computadora`.`Antivirus`" => "Antivirus",
		"`Computadora`.`TeamviewerID`" => "TeamviewerID",
		"`Computadora`.`Notas`" => "Notas",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Computadora`.`id`" => "ID",
		"`Computadora`.`Empleado`" => "Nombre Empleado",
		"`Computadora`.`Marca`" => "Marca Comp.",
		"`Computadora`.`Modelo`" => "Comp. Modelo",
		"`Computadora`.`Serie`" => "# Serie",
		"`Computadora`.`Hedset`" => "Headset",
		"`Computadora`.`Monitor`" => "Monitor Externo",
		"`Computadora`.`campo1`" => "Campo 1",
		"`Computadora`.`campo2`" => "Campo 2",
		"`Computadora`.`NombreComp`" => "Nombre Comp.",
		"`Computadora`.`Antivirus`" => "Antivirus",
		"`Computadora`.`TeamviewerID`" => "Teamviewer ID",
		"`Computadora`.`Notas`" => "Notas",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Computadora`.`id`" => "id",
		"`Computadora`.`Empleado`" => "Empleado",
		"`Computadora`.`Marca`" => "Marca",
		"`Computadora`.`Modelo`" => "Modelo",
		"`Computadora`.`Serie`" => "Serie",
		"`Computadora`.`Hedset`" => "Hedset",
		"`Computadora`.`Monitor`" => "Monitor",
		"`Computadora`.`campo1`" => "campo1",
		"`Computadora`.`campo2`" => "campo2",
		"`Computadora`.`NombreComp`" => "NombreComp",
		"`Computadora`.`Antivirus`" => "Antivirus",
		"`Computadora`.`TeamviewerID`" => "TeamviewerID",
		"`Computadora`.`Notas`" => "Notas",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Computadora` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Computadora_view.php";
	$x->RedirectAfterInsert = "Computadora_view.php";
	$x->TableTitle = "Computadoras";
	$x->TableIcon = "resources/table_icons/laptop.png";
	$x->PrimaryKey = "`Computadora`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Nombre Empleado", "Marca Comp.", "Comp. Modelo", "# Serie", "Headset", "Monitor Externo", "Campo 1", "Campo 2", "Nombre Comp.", "Antivirus", "Teamviewer ID", "Notas");
	$x->ColFieldName = array('Empleado', 'Marca', 'Modelo', 'Serie', 'Hedset', 'Monitor', 'campo1', 'campo2', 'NombreComp', 'Antivirus', 'TeamviewerID', 'Notas');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Computadora_templateTV.html';
	$x->SelectedTemplate = 'templates/Computadora_templateTVS.html';
	$x->TemplateDV = 'templates/Computadora_templateDV.html';
	$x->TemplateDVP = 'templates/Computadora_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Computadora`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Computadora' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Computadora`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Computadora' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Computadora`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Computadora_init
	$render=TRUE;
	if(function_exists('Computadora_init')) {
		$args=array();
		$render=Computadora_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Computadora_header
	$headerCode='';
	if(function_exists('Computadora_header')) {
		$args=array();
		$headerCode=Computadora_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Computadora_footer
	$footerCode='';
	if(function_exists('Computadora_footer')) {
		$args=array();
		$footerCode=Computadora_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>